"""Add DISCONNECT Enum for Meeting module

Revision ID: c2febf167742
Revises: 9cb2eab154a4
Create Date: 2026-07-19 19:48:15.419417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2febf167742'
down_revision: Union[str, Sequence[str], None] = '9cb2eab154a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
